src/Entity/Model.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ModelRepository")
 */
class Model extends Content
{
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PriceModel", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="model_id")
     */
    private $priceModel;
    

    public function setPriceModel(?PriceModel $model): self
    {
        $this->priceModel = $model;

        return $this;
    }
    
    public function getPriceBrand():?PriceBrand
    {
        $model = $this->getPriceModel();
        if (!$model) {
            return null;
        }
        $brand = $model->getPriceBrand();
        if (!$brand) {
            return null;
        }
        return $brand;
    }
    
    public function getPriceModel():?PriceModel
    {
        return $this->priceModel;
    }
    
    public function getModelName():string
    {
        $model = $this->getPriceModel();
        if (!$model) {
            return '';
        }
        return $model->getName();
    }
    
    public function getBrandName():string
    {
        $brand = $this->getPriceBrand();
        if (!$brand) {
            return '';
        }
        return $brand->getName();
    }
    
    public function getBrandAndModelName():string
    {
        $model = $this->getPriceModel();
        if (!$model) {
            return '';
        }
        return $this->getBrandName().' '.$model->getName();
    }
    
    public function getModel(): ?Model
    {
        return $this;
    }
    
    public function getBrand(): ?Brand
    {
        $parent = $this->getParent();
        if ($parent instanceof Brand) {
            return $parent;
        }
        return null;
    }
    
    public function getBrandModelWithTranslation():string
    {
        return $this->getPriceModel()->getBrandModelWithTranslation();
    }
}

src/Entity/News.php
<?php

namespace App\Entity;

use App\Entity\Contracts\PageInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class News implements PageInterface
{
    use Traits\ModifyDateTrait;
    use Traits\LocationTrait;

    public const BASE_PATH = '/news/';
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meta_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meta_description;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     */
    private $sort;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $images;

    /**
     * @ORM\Column(type="text")
     */
    private $short_text;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_views=0;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_like=0;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_dislike=0;

    public function __construct()
    {
        $this->date = time();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(string $meta_title): self
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(string $meta_description): self
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getSort(): ?int
    {
        return $this->sort;
    }

    public function setSort(int $sort): self
    {
        $this->sort = $sort;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function getImagesArray(): ?array
    {
        if ( ! $this->images) {
            return [];
        }
        $images = explode('|',$this->images);
        foreach ($images as &$image) {
            $image =strstr($image,'<<<',true);
        }
        return $images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getShortText(): ?string
    {
        return $this->short_text;
    }

    public function setShortText(string $short_text): self
    {
        $this->short_text = $short_text;

        return $this;
    }

    public function getCountViews(): ?int
    {
        return $this->count_views;
    }

    public function setCountViews(int $count_views): self
    {
        $this->count_views = $count_views;

        return $this;
    }

    public function getCountLike(): ?int
    {
        return $this->count_like;
    }

    public function setCountLike(int $count_like): self
    {
        $this->count_like = $count_like;

        return $this;
    }

    public function getCountDislike(): ?int
    {
        return $this->count_dislike;
    }

    public function setCountDislike(int $count_dislike): self
    {
        $this->count_dislike = $count_dislike;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->date;
    }

    public function setDate(int $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPath(): ?string
    {
        return self::BASE_PATH . $this->getId() . '/';
    }

    public function getH1(): ?string
    {
        return $this->getName();
    }

    public function getBrandName(): string
    {
        return '';
    }

    /**
     * Возвращает путь из таблицы content или объект PageInterface
     * @return string|PageInterface
     */
    public function getParent()
    {
        return self::BASE_PATH;
    }

    public function getBrandAndModelName(): string
    {
        return '';
    }
}

templates/v2/pages/brand.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %}{{ page.metaTitle ?? (page.h1~' - кузовной центр '~page.brandName~' Детейлингофъ') }}{% endblock %}
{% block body %}
    {{ include('v2/blocks/section/services_categories.html.twig') }}
    {{ include('v2/blocks/section/auto-models.html.twig', { brand: page.priceBrand }) }}
    {% embed 'v2/embed/black-services-block.html.twig' %}
        {% block content %}
            {{ price_list(page) }}
            {{ naschiraboty_slider(page) }}
        {% endblock %}
    {% endembed %}
    {{ seo_block(page.text) }}
{% endblock %}

templates/v2/pages/model.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %}{{ page.metaTitle ?? (page.h1~' - кузовной центр '~page.brandName~' Детейлингофъ') }}{% endblock %}
{% block body %}
    {{ include('v2/blocks/section/services_categories.html.twig') }}
    {% embed 'v2/embed/black-services-block.html.twig' %}
        {% block content %}
            {{ price_list(page) }}
            {{ naschiraboty_slider(page) }}
        {% endblock %}
    {% endembed %}
    {{ seo_block(page.text) }}
{% endblock %}

templates/v2/pages/recaptcha.html.twig
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    <div style="font-size: 1.5rem;" class="text-center p-3">
        <div class="container d-flex justify-content-center">
            <div class="row">
                <form method="post">
                    <div class="form-group">
                        <p>Пожалуйста, поставьте галочку и нажмите кнопку Войти</p>
                        <div class="g-recaptcha d-flex justify-content-center" data-sitekey="{{ gg_recaptcha_site_key }}">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Войти</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://www.google.com/recaptcha/api.js"></script>
    </body>
</html>

templates/v2/pages/root-service.html.twig
{% extends 'v2/base.html.twig' %}

{% block body %}
    {% embed 'v2/embed/black-services-block.html.twig' %}
        {% block content %}
            {{ price_list(page) }}
        {% endblock %}
    {% endembed %}
    {{ seo_block(page.text) }}
{% endblock %}

templates/v2/pages/service.html.twig
{% extends 'v2/base.html.twig' %}
{% block title %}{{ page.metaTitle ?? (page.h1~' - кузовной центр '~page.brandName~' Детейлингофъ') }}{% endblock %}

{% block body %}
    {% embed 'v2/embed/black-services-block.html.twig' %}
        {% block content %}
            {{ price_list(page) }}
            {{ naschiraboty_slider(page) }}
        {% endblock %}
    {% endembed %}
    {{ seo_block(page.text) }}
{% endblock %}

templates/v2/pages/simple.html.twig
{% extends 'v2/base.html.twig' %}

{% block body %}
    {{ include('v2/blocks/section/content.html.twig',{text:page.text }) }}
{% endblock %}

templates/v2/pages/vacancy.html.twig
{% extends 'v2/base.html.twig' %}

{% block body %}
    {{ include('v2/blocks/section/content.html.twig',{text: page.text }) }}
{% endblock %}